resources:
  repositories:
  - repository: K8sPartnerExtensionTest
    type: git
    endpoint: K8sPartnerExtension
    name: One/compute-HybridMgmt-K8sPartnerExtensionTest

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

jobs:
- job: LintModifiedExtensions
  displayName: "CLI Linter on Modified Extensions"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
    - checkout: K8sPartnerExtensionTest
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - bash: |
        set -ev

        # prepare and activate virtualenv
        pip install virtualenv
        python -m virtualenv venv/
        source ./venv/bin/activate

        # clone azure-cli
        pip install azdev

        azdev --version

      #   azdev setup -c ../azure-cli -r ./

      #   # overwrite the default AZURE_EXTENSION_DIR set by ADO
      #   AZURE_EXTENSION_DIR=~/.azure/cliextensions az --version

      #   AZURE_EXTENSION_DIR=~/.azure/cliextensions python scripts/ci/verify_linter.py
      # displayName: "CLI Linter on Modified Extension"
      # env:
      #   ADO_PULL_REQUEST_LATEST_COMMIT: $(System.PullRequest.SourceCommitId)
      #   ADO_PULL_REQUEST_TARGET_BRANCH: $(System.PullRequest.TargetBranch)