resources:
  repositories:
  - repository: K8sPartnerExtensionTest
    type: git
    endpoint: K8sPartnerExtension
    name: One/compute-HybridMgmt-K8sPartnerExtensionTest

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  K8sExtensionTestPath: $(Agent.BuildDirectory)/compute-HybridMgmt-K8sPartnerExtensionTest
  CLIPath: $(Agent.BuildDirectory)/azure-cli-extensions

jobs:
- job: K8sExtensionIntegrationTest 
  displayName: "k8-extension Integration Test Suite"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
    - checkout: K8sPartnerExtensionTest
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - bash: |
        set -ev

        # prepare and activate virtualenv
        pip install virtualenv
        python -m virtualenv venv/
        source venv/bin/activate

        # clone azure-cli
        pip install azdev

        azdev --version
        azdev setup -c $(K8sExtensionTestPath) -e k8s-extension
        azdev extension build k8s-extension

        ls $(K8sExtensionTestPath)

      workingDirectory: $(K8sExtensionTestPath)
      displayName: "Setup and build k8s-extension with azdev"