resources:
  repositories:
  - repository: K8sPartnerExtensionTest
    type: git
    endpoint: K8sPartnerExtension
    name: One/compute-HybridMgmt-K8sPartnerExtensionTest

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  K8S_EXTENSION_REPO_PATH: $(Agent.BuildDirectory)/s/compute-HybridMgmt-K8sPartnerExtensionTest
  CLI_REPO_PATH: $(Agent.BuildDirectory)/s/azure-cli-extensions
  EXTENSION_NAME: "k8sconfiguraiton"

jobs:
- job: K8sExtensionIntegrationTest 
  displayName: "k8-extension Integration Test Suite"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
    - checkout: K8sPartnerExtensionTest
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - bash: |
        set -ev

        # prepare and activate virtualenv
        pip install virtualenv
        python3 -m venv env/
        source env/bin/activate

        # clone azure-cli
        pip install azdev

        ls $(CLI_REPO_PATH)

        azdev --version
        azdev setup -r $(CLI_REPO_PATH) -e $(EXTENSION_NAME)
        azdev extension build $(EXTENSION_NAME)

      workingDirectory: $(CLI_REPO_PATH)
      displayName: "Setup and Build k8s-extension with azdev"
    
    - bash: |
        cp dist/* $(K8S_EXTENSION_REPO_PATH)/extensions
      workingDirectory: $(CLI_REPO_PATH)
      displayName: "Copy the Built .whl to Extension Test Path"

    # - bash: |

    #   workingDirectory $(K8S_EXTENSION_REPO_PATH)
    #   displayName: "Generate a settings.json file based on extension value"

    # - powershell:
        