resources:
  repositories:
  - repository: K8sPartnerExtensionTest
    type: git
    endpoint: K8sPartnerExtension
    name: One/compute-HybridMgmt-K8sPartnerExtensionTest

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  K8sExtensionTestPath: $(Agent.BuildDirectory)/s/compute-HybridMgmt-K8sPartnerExtensionTest
  CLIPath: $(Agent.BuildDirectory)/s/azure-cli-extensions

jobs:
- job: K8sExtensionIntegrationTest 
  displayName: "k8-extension Integration Test Suite"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
    - checkout: K8sPartnerExtensionTest
    
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
    - bash: |
        set -ev

        # prepare and activate virtualenv
        pip install virtualenv
        python3 -m venv env/
        source env/bin/activate

        # clone azure-cli
        pip install azdev

        ls $(CLIPath)

        azdev --version
        azdev setup -c $(CLIPath) -e k8s-extension
        azdev extension build k8s-extension

      workingDirectory: $(CLIPath)
      displayName: "Setup and Build k8s-extension with azdev"
    
    - bash: |
        cp dist/* $(K8sExtensionTestPath)/extensions
      workingDirectory: $(CLIPath)